from django.urls import path
from . import views

urlpatterns =[
    # 1. Make the Traffic Cop the front door
    path('', views.dashboard_redirect, name='home'),
    
    # 2. Move the colorful dashboard to its own path
    path('dashboard/', views.order_list, name='order_list'),
    
    # ... keep all your other paths exactly as they are ...
    path('create/', views.create_order, name='create_order'),

    # path('', views.order_list, name='order_list'),
    # path('create/', views.create_order, name='create_order'),
    path('add_customer/', views.create_customer, name='create_customer'),
    path('edit/<int:order_id>/', views.edit_order, name='edit_order'),
    path('delete/<int:order_id>/', views.delete_order, name='delete_order'),
    path('super-admin/', views.super_admin_dashboard, name='super_admin_dashboard'), 
    path('super-admin/add/', views.add_business, name='add_business'),
    path('super-admin/toggle/<int:business_id>/', views.toggle_business_status, name='toggle_business_status'),
    path('super-admin/edit/<int:business_id>/', views.edit_business, name = 'edit_business'),
    path('manage-services/', views.manage_services, name = 'manage_services'),
    path('manage-staff/', views.manage_staff, name='manage_staff'),
    path('my-branches/', views.my_branches, name='my_branches'),
    path('switch-branch/<int:business_id>/', views.switch_business, name='switch_business'),
    path('dashboard-redirect/', views.dashboard_redirect, name='dashboard_redirect'),
    path('suspended/', views.business_suspended, name='business_suspended'),
    path('tasks/', views.task_list, name='task_list'),
    path('task-complete/<int:task_id>/', views.complete_task, name='complete_task'),
    path('stock-requests/', views.stock_request_lists, name='stock_request_list'),
    path('manage-stock/', views.manage_stock_requests, name='manage_stock_requests'),
    path('update-stock/<int:request_id>/', views.update_stock_status, name='update_stock_status'),
    path('system-settings/', views.system_settings, name='system_settings'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('system/maintenance/', views.maintenance_control, name='maintenance_control'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/edit/<int:customer_id>/', views.edit_customer, name='edit_customer'),
    path('business/settings/', views.business_settings, name='business_settings'),
    path('complaints/', views.complaint_list, name='complaint_list'),
    path('complaints/resolve/<int:complaint_id>/', views.resolve_complaint, name='resolve_complaint'),
    path('schedule/', views.schedule_list, name='schedule_list'),
    path('schedule/delete/<int:shift_id>/', views.delete_shift, name='delete_shift'),
    path('reports/', views.branch_reports, name='branch_reports'),
    path('customers/delete/<int:customer_id>/', views.delete_customer, name='delete_customer'),
    path('order/receipt/<int:order_id>/', views.order_receipt, name='order_receipt'),
    path('register/', views.public_register, name='public_register'),
    path('my-laundry/', views.customer_dashboard, name='customer_dashboard'),   
    path('dashboard-redirect/', views.dashboard_redirect, name='dashboard_redirect'),
    path('my-laundry/history/', views.customer_order_history, name='customer_order_history'),
    path('my-laundry/new/', views.customer_request_pickup, name='customer_request_pickup'),
    path('my-laundry/complaint/', views.customer_raise_complaint, name='customer_raise_complaint'),
    path('order/<int:order_id>/pay/', views.accept_payment, name='accept_payment'),
    path('my-laundry/pay/<int:order_id>/', views.customer_payment, name='customer_payment'),
    path('my-laundry/rate/<int:order_id>/', views.rate_service, name='rate_service'),
    path('manage/branches/', views.my_branches, name='manage_branches'),
    path('manage/add-branch/', views.add_business, name='add_business'),
    path('admin/roles/', views.manage_roles, name='manage_roles'),
    path('admin/roles/add/', views.edit_role, name='add_role'),
    path('admin/roles/edit/<int:role_id>/', views.edit_role, name='edit_role'),
    path('admin/roles/delete/<int:role_id>/', views.delete_role, name='delete_role'),
    path('order/approve/<int:order_id>/', views.approve_order, name='approve_order'),
    path('order/update-status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('rates/', views.rate_card, name='rate_card'),
    path('manage-services/edit/<int:service_id>/', views.edit_service, name='edit_service'),
    path('create/<int:service_id>/', views.create_order, name='create_order'),
    path('admin/users/', views.admin_user_list, name='admin_user_list'),
    path('manage-staff/permissions/<int:user_id>/', views.edit_user_permissions, name='edit_user_permissions'),
    path('admin/users/delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path('customer/profile/', views.customer_profile, name='customer_profile'), 
    path('customer/change-password/', views.change_password, name='change_password'),   
    path('staff/register-customer/', views.customer_register, name='customer_register'),
    path('delete-business/<int:branch_id>/', views.delete_branch, name='delete_business'),
    path('manage-staff/edit/<int:user_id>/', views.edit_staff, name='edit_staff'),
    path('collect-payment/<int:order_id>/', views.collect_payment, name='collect_payment'),
    path('my-laundry/complaints-history/', views.customer_complaint_list, name='customer_complaint_list'),
    path('complaints/resolve/<int:complaint_id>/', views.resolve_complaint, name='resolve_complaint'),
    path('send-otp-email/', views.send_otp_email, name='send_otp_email'),
    path('verify-registration-otp/', views.verify_registration_otp, name='verify_registration_otp'),
    path('check-username/', views.check_username_availability, name='check_username_availability'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('send-reset-otp/', views.send_reset_otp, name='send_reset_otp'),
    path('verify-reset-otp/', views.verify_reset_otp, name='verify_reset_otp'),
    path('profile/', views.staff_profile, name='staff_profile'),
    path('send-email-change-otp/', views.send_email_change_otp, name='send_email_change_otp'),
    path('', views.public_home, name='public_home'),
    path('manage-reviews/', views.manage_reviews, name='manage_reviews'),
    path('toggle-review/<int:order_id>/', views.toggle_review_approval, name='toggle_review_approval'),
    ]

