# Generated by Django 5.2.9 on 2025-12-31 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_laundrybusiness_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.laundrybusiness'),
        ),
    ]
