# Generated by Django 5.2.9 on 2025-12-31 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_service_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.laundrybusiness'),
        ),
        migrations.AddField(
            model_name='order',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.laundrybusiness'),
        ),
    ]
