# Generated by Django 5.2.9 on 2026-01-01 08:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_stockreqest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockReqest',
            new_name='StockRequest',
        ),
    ]
