# Generated by Django 5.2.9 on 2026-01-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_stockreqest_stockrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LaundryPro', max_length=100)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Lock the site for non-admins')),
                ('global_announcement', models.TextField(blank=True, help_text='Message shown on top of every page')),
            ],
        ),
    ]
