# Generated by Django 5.2.9 on 2026-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_name',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], default='Morning', max_length=20),
        ),
    ]
