# Generated by Django 5.2.9 on 2026-01-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_phone_number_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions from customer', null=True),
        ),
    ]
