# Generated by Django 5.2.9 on 2026-01-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_estimated_delivery_order_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='business',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Dry Cleaning', 'Dry Cleaning'), ('Washing', 'Washing & Laundry'), ('Premium', 'Premium / Couture'), ('Home', 'Home Care (Curtains/Sofa)'), ('Shoes', 'Shoe & Bag Cleaning')], default='Washing', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text="Features like '100% Organic', 'Steam Ironing'"),
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.CharField(choices=[('pc', 'Per Piece'), ('kg', 'Per Kg'), ('sqft', 'Per Sq. Ft'), ('pair', 'Per Pair'), ('seat', 'Per Seat')], default='pc', max_length=10),
        ),
    ]
