# Generated by Django 5.2.9 on 2026-01-13 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_remove_service_business_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.laundrybusiness'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
