# Generated by Django 5.2.9 on 2026-01-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_service_business_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(choices=[('Morning', 'Morning (9:00 AM - 12:00 PM)'), ('Afternoon', 'Afternoon (12:00 PM - 4:00 PM)'), ('Evening', 'Evening (4:00 PM - 8:00 PM)')], default='Morning', max_length=20),
        ),
    ]
