# Generated by Django 5.2.9 on 2026-01-20 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_pickup_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_collected_by',
            field=models.ForeignKey(blank=True, help_text='The staff member who collected the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
