# Generated by Django 5.2.9 on 2026-01-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_payment_collected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.CharField(choices=[('Per Piece', 'Per Piece'), ('Per Kg', 'Per Kg'), ('Per Pair', 'Per Pair'), ('Per Meter', 'Per Meter'), ('Per Sq. Ft', 'Per Sq. Ft')], default='Per Piece', max_length=50),
        ),
    ]
