# Generated by Django 5.2.9 on 2026-02-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_order_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_note',
            field=models.TextField(blank=True, help_text="Manager's reply to the customer", null=True),
        ),
    ]
