# Generated by Django 5.2.9 on 2026-03-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name_backup',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
