# Generated by Django 5.2.9 on 2026-03-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_customer_name_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_review_approved',
            field=models.BooleanField(default=False),
        ),
    ]
