# Generated by Django 6.0.4 on 2026-05-08 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_is_review_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='is_quick_booking',
            field=models.BooleanField(default=False, help_text='Indicates if the order was placed via Quick Booking.'),
        ),
        migrations.AddField(
            model_name='order',
            name='temporary_customer',
            field=models.BooleanField(default=True, help_text='Marks if the customer is temporary (Quick Booking).'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='orders.area')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.laundrybusiness')),
            ],
        ),
    ]
