# Generated by Django on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_area_order_is_quick_booking_order_temporary_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_note',
            field=models.TextField(blank=True, help_text='Customer note for quick booking or special instructions.', null=True),
        ),
    ]
