# Generated by Django 6.0.4 on 2026-05-13 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_order_customer_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='fa-shirt', help_text="FontAwesome icon class e.g., 'fa-shirt', 'fa-pants'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_note',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='quantity × sum of service prices', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.clothingitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_order', models.DecimalField(decimal_places=2, help_text='Price snapshot at time of order', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.service')),
            ],
            options={
                'unique_together': {('order_item', 'service')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='services',
            field=models.ManyToManyField(help_text='Services assigned to this clothing item', through='orders.OrderItemService', to='orders.service'),
        ),
    ]
